[package]
name = "wavesexchange_address"
version = "0.1.0"
authors = ["Dmitry Shuranov <dvshur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
blake2 = "0.9"
sha3 = "0.9"
bs58 = "0.4"
